use crate::syntax::repr::Repr;
use crate::syntax::test::key;

pub(super) fn expected() -> Vec<Repr> {
    vec![
        key(""),
        key(" "),
        key("("),
        key(")"),
        key("["),
        key("]"),
        key("{"),
        key("}"),
        key("<"),
        key(">"),
        key("\\"),
        key("|"),
        key("/"),
        key("'"),
        key("\""),
        key(":"),
        key(";"),
        key("!"),
        key("?"),
        key("."),
        key(","),
        key("`"),
        key("~"),
        key("@"),
        key("#"),
        key("$"),
        key("%"),
        key("^"),
        key("&"),
        key("*"),
        key("-"),
        key("+"),
        key("_"),
        key("="),
        key("->"),
        key("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"),
        key("a"),
        key("Z"),
        key("abc"),
        key("Xyz"),
        key("0"),
        key("0123456789"),
        key("\"a"),
        key("'a"),
        key("to_be_or_not_to_be"),
        key("R34G148B83"),
        key("a%"),
        key("%a"),
        key("&1"),
        key(":a"),
        key("a:"),
        key(":1"),
        key("+1"),
        key("+="),
        key("+nightly"),
        key("-1.1"),
        key("->"),
        key("--stat"),
        key("^"),
        key(" "),
        key(" 'a  b"),
        key("^_^\"\""),
        key(" ' '^_^\"^_^\" ' '"),
        key(" ' '^_^\"^_^\" ' '"),
    ]
}
