// @(v) represents the set of outputs generated by evaluating v
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq, Hash)]
pub struct Abstract<V> {
    pub value: V,
}

impl<V> Abstract<V> {
    pub fn new(value: V) -> Self {
        Self { value }
    }
}
