[package]
name = "airlang"
version = "0.26.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Air is a universal, reliable, and lean programming language."
repository = "https://github.com/LambdaAlpha/airlang_rs"
keywords = ["programming-language", "dsl", "ast", "ir", "vm"]
categories = ["compilers"]

[[test]]
name = "syntax"

[[test]]
name = "semantics"

[[test]]
name = "bench"

[[bench]]
name = "syntax"
harness = false

[[bench]]
name = "semantics"
harness = false

[lints]
workspace = true

# faster hash map
[dependencies.rustc-hash]
version = "2"

# integer and decimal
[dependencies.num-traits]
version = "0.2"

# integer
[dependencies.num-bigint]
version = "0.4"

# integer
[dependencies.num-integer]
version = "0.1"

# decimal
[dependencies.bigdecimal]
version = "0.4"

# key
[dependencies.string_cache]
version = "0.9"
default-features = false
features = []

# syntax parsing
[dependencies.winnow]
version = "1"

# val generation
[dependencies.rand]
version = "0.10"

# fact
[dependencies.internment]
version = "0.8"
default-features = false
features = ["arc"]

# const str
[dependencies.const_format]
version = "0.2"

# derive
[dependencies.derive_more]
version = "2"
default-features = false
features = [
    "std",
    "from",
    "try_from",
    "into",
    "try_into",
    "as_ref",
    "deref",
    "deref_mut",
    "is_variant",
    "unwrap",
    "try_unwrap",
    "constructor",
    "into_iterator",
    "debug",
    "display",
]

# macro, test, bench, log
[dev-dependencies.airlang_dev]
path = "../dev"
